### PR TITLE
feat : Address -> UserName / Register Function

### LINKED ISSUE #13: Mapping address to Readable names
This issue is with direct implications for the [Subvid stream smart contracts issue](https://github.com/aditya172926/Subvid_stream_contracts/issues/4)

On Web3 we do have our wallet addresses which uniquely identify us. But we as humans are very used to dealing with readable names.

image

### PR DESCRIPTION
**Pull request by ocdbytes**
- Address -> UserName functionality completed.
- Added a register function to set UserName.
- Deployed the updated contract : 0xd84D2801b8D01Fb5435231EF1850DF09FA3d80bD
- Updated the new address in Readme.md

Please Add hacktoberfest-accepted tag in. this issue 
@aditya172926 

</img>

### CODE REVIEW

**Comment by aditya172926** [comment]
There are some conflicts in your pull request. Do a git pull in your repo. It should be just a case of formatting issue and then push it to the same branch once again.
I'll review the PR again @Arun89-crypto

**Comment by aditya172926** [comment]
Also I tried the preview of this PR. There are some issues coming up in the website and while executing the contract transaction.

The wallet cannot figure out the gas required for the transaction. So there is some issues in your deployed contract.
Please resolve this issues and I'll check it out.
Let me know if you require any help @Arun89-crypto

**Comment by ocdbytes** [comment]
Regarding that gas issue I have added a functionality that will require you to register as a user with username then only you will be able to use the functions @aditya172926 
I have also added a line saying that **You need to register to use the wallet functionality** in the modal that appears when we connect the wallet

**Comment by ocdbytes** [comment]
These files i have changed because I have made some changes in the contract and then redeployed the contract I will try to pull once again and then create a PR

**Comment by ocdbytes** [comment]
Conflicts Resolved / Code changes done ✅
@aditya172926 

You can check the Vercel deployment to test.
Link : https://subvid-stream-lf3zhzf0e-aditya172926.vercel.app

Please merge it and add the hacktoberfest-accepted tag

**Comment by aditya172926** [comment]
LGTM 👍

**Pull request merged**
